Setting up database tables and seed data
GenerateNU/platnm pull request #16
Opened 2024-09-17 02:58 UTC by ddusichka

This PR adds a migration script and seed data for several of the tables we discussed within our schema.

Tables: `user`, `artist`, `genre`, `album`, `album_artist`, `track`, `track_artist`, `review`

Tested using local supabase migration, which successfully ran migration script and populated data for each table
![image](https://github.com/user-attachments/assets/f4809ca5-ae4e-4e31-a5ba-c6e0c7c12463)

Comments and questions welcome!!

2024-09-17 21:38 UTC, garrettladley requested changes

2024-09-17 21:38 UTC, garrettladley commented on backend/internal/supabase/migrations/20240917002108_base_schema.sql
> +    username text not null,
unique?

2024-09-17 21:38 UTC, garrettladley commented on backend/internal/supabase/migrations/20240917002108_base_schema.sql
> +    media_id integer not null, -- can't foreign key to album or track because it could be either
🔥

2024-09-17 21:38 UTC, garrettladley commented on backend/internal/supabase/migrations/20240917002108_base_schema.sql
> +    media_id integer not null, -- can't foreign key to album or track because it could be either
polymorphic if you will

2024-09-18 02:17 UTC, garrettladley approved these changes

2024-09-18 02:17 UTC, ddusichka commented on backend/internal/supabase/migrations/20240917002108_base_schema.sql
> +    username text not null,
so true https://github.com/GenerateNU/platnm/pull/16/commits/7c69270d151f143476ec25ebc5c80cef812f3dc9

2024-09-18 02:29 UTC, gaikwadsid commented
W

2024-09-18 02:30 UTC, merged